openapi: 3.0.0
info:
  title: API 文件
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.0
servers:
  - url: http://localhost:4000
    #- url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    userId:
      - in: path
        name: userId
        required: true
        schema:
          type: interger
  schemas:
    signin:
      oneOf:
        - $ref: '#/components/schemas/signinNative'
        - $ref: '#/components/schemas/signinFb'
    signinNative:
      type: object
      properties:
        provider:
          type: string
        email:
          type: string
        password:
          type: string
    signinFb:
      type: object
      properties:
        provider:
          type: string
        email:
          type: string
  examples:
    signinNative:
      value:
        provider: native
        email: test@test.com
        password: test
    signinFB:
      value:
        provider: facebook
        access_token: EAACEdEose0cBAHc6hv9kK8bMNs4XTrT0kVC1RgDZCVBptXW12AI
tags:
  - name: products
  - name: campaigns
  - name: users
  - name: fans
  - name: games

paths:
  #GET
  /marketing/campaigns:
    get:
      tags:
        - campaigns
      summary: Returns a list of campaigns
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                        proudct_id:
                          type: integer
                          example: 100
                        picture:
                          type: string
                          example: https://api.appworks-school.tw/assets/201807242228/keyvisual.jpg
                        story:
                          type: string
                          example: 於是 我也想要給你 一個那麼美好的自己。 不朽《與自己和好如初》
  #GET帶query
  /products/details:
    get:
      tags:
        - products
      summary: List of products grouped by category
      parameters:
        - in: query
          name: id
          required: true
          description: The category of the products to return.
          schema:
            type: integer
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
  #GET帶parameters(選單)
  /products/{category}:
    get:
      tags:
        - products
      summary: List of products grouped by category
      parameters:
        - in: path
          name: category
          required: true
          description: The category of the products to return.
          schema:
            type: string
            enum: #建立選單
              - all
              - women
              - men
              - accessories
              - search
              - details
        - in: query
          name: id
          description: The category of the products to return.
          schema:
            type: integer
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
  #POST有多種request格式
  /user/signin:
    post:
      tags:
        - users
      summary: post signup data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/signin'
            examples:
              native:
                $ref: '#/components/examples/signinNative'
              fb:
                $ref: '#/components/examples/signinFB'
      responses:
        '200':
          description: user token and info
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                      access_expired:
                        type: string
                      user:
                        type: object
                        properties:
                          provider:
                            type: string
                          name:
                            type: string
                          email:
                            type: string
                          picture:
                            type: string
              example:
                value:
                  data:
                    access_token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6joiYXJ0aHVIjoxNjEzNTY3MzA0fQ.6EPCOfBGynidAfpVqlvbHGWHCJ5LZLtKvPaQ
                    access_expired: 3600
                    user:
                      provider: facebook
                      name: Pei
                      email: pei@appworks.tw
                      picture: https://schoolvoyage.ga/images/123498.png
  #同個路徑下不同method, 可共用parameter
  /like/{userId}:
    parameters:
      - $ref: '#/components/parameters/userId'
    get:
      responses:
        '200':
          description: User likes product deleted.
    post:
      responses:
        '200':
          description: User likes product deleted.
    put:
      deprecated: true #標示已棄用
    delete:
      responses:
        '200':
          description: User likes product deleted.
  #Header帶token
  /user/profile:
    get:
      tags:
        - users
      summary: user profile
      description: user info and token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: user info and token
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        provider:
                          type: string
                          example: facebook
                        name:
                          type: string
                          example: Pei
                        email:
                          type: string
                          example: pei@appworks.tw
                        picture:
                          type: string
                          example: https://schoolvoyage.ga/images/123498.png
